# Generated by Django 4.1.1 on 2022-10-03 13:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_conteudo_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem_capa',
            field=models.ImageField(
                blank=True, null=True, upload_to='static/blog/'
            ),
        ),
        migrations.AddField(
            model_name='post',
            name='resumo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
