# Generated by Django 4.1.1 on 2022-10-17 19:51

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(
                verbose_name=datetime.datetime(
                    2022,
                    10,
                    17,
                    19,
                    51,
                    58,
                    616087,
                    tzinfo=datetime.timezone.utc,
                )
            ),
        ),
    ]
