# Generated by Django 4.1.1 on 2022-10-19 13:29

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_data_publicacao_assunto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSituacao',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('data', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(
                verbose_name=datetime.datetime(
                    2022,
                    10,
                    19,
                    13,
                    29,
                    18,
                    49728,
                    tzinfo=datetime.timezone.utc,
                )
            ),
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('nome', models.CharField(max_length=50)),
                (
                    'posts',
                    models.ManyToManyField(
                        through='blog.PostSituacao', to='blog.post'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='postsituacao',
            name='post',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='blog.post'
            ),
        ),
        migrations.AddField(
            model_name='postsituacao',
            name='post_situacao',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='post_situacao',
                to='blog.post',
            ),
        ),
        migrations.AddField(
            model_name='postsituacao',
            name='situacao',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='blog.situacao'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='postsituacao',
            unique_together={('post', 'situacao')},
        ),
    ]
